### ISSUE TITLE
StackOverflowError when too many columns and records

### ISSUE THREAD

**Issue by khalil00** [got5/tapestry5-jquery#359]
I have a problem with a datatable which have 9 columns and about 1000 records.
It seems that the Tomcat JVM stack size doesn't support this amount of recursive calls :

```
[ERROR] 2015-04-02 17:03:51,778 [] [] [http-bio-8080-exec-5] [org.apache.tapestry5.ioc.Registry] : java.lang.StackOverflowError
[ERROR] 2015-04-02 17:03:51,778 [] [] [http-bio-8080-exec-5] [org.apache.tapestry5.ioc.Registry] : Operations trace:
[ERROR] 2015-04-02 17:03:51,778 [] [] [http-bio-8080-exec-5] [org.apache.tapestry5.ioc.Registry] : [ 1] Triggering event 'data' on inquiry/PaymentsManagementPage:datatable.datatable
[ERROR] 2015-04-02 17:03:51,806 [] [] [http-bio-8080-exec-5] [org.apache.tapestry5.services.TapestryModule.RequestExceptionHandler] : Processing of request failed with uncaught exception: java.lang.StackOverflowError
java.lang.StackOverflowError: null
	at org.apache.tapestry5.ioc.internal.services.PerthreadManagerImpl.getPerthreadMap(PerthreadManagerImpl.java:90) ~[tapestry-ioc-5.3.7.jar:na]
	at org.apache.tapestry5.ioc.internal.services.PerthreadManagerImpl.access$200(PerthreadManagerImpl.java:33) ~[tapestry-ioc-5.3.7.jar:na]
	at org.apache.tapestry5.ioc.internal.services.PerthreadManagerImpl$2.exists(PerthreadManagerImpl.java:192) ~[tapestry-ioc-5.3.7.jar:na]
	at org.apache.tapestry5.ioc.internal.services.PerThreadServiceCreator.createObject(PerThreadServiceCreator.java:44) ~[tapestry-ioc-5.3.7.jar:na]
	at $PageRenderQueue_14dff6325dcc.delegate(Unknown Source) ~[na:na]
	at $PageRenderQueue_14dff6325dcc.addPartialRenderer(Unknown Source) ~[na:na]
	at $PageRenderQueue_14dff63258f1.addPartialRenderer(Unknown Source) ~[na:na]
	at org.got5.tapestry5.jquery.internal.DefaultDataTableModel$3.renderMarkup(DefaultDataTableModel.java:451) ~[DefaultDataTableModel$3.class:na]
	at org.apache.tapestry5.internal.services.PageRenderQueueImpl$Bridge.renderMarkup(PageRenderQueueImpl.java:62) ~[tapestry-core-5.3.7.jar:na]
	at org.got5.tapestry5.jquery.internal.DefaultDataTableModel$3.renderMarkup(DefaultDataTableModel.java:453) ~[DefaultDataTableModel$3.class:na]
	at org.apache.tapestry5.internal.services.PageRenderQueueImpl$Bridge.renderMarkup(PageRenderQueueImpl.java:62) ~[tapestry-core-5.3.7.jar:na]
	at org.got5.tapestry5.jquery.internal.DefaultDataTableModel$3.renderMarkup(DefaultDataTableModel.java:453) ~[DefaultDataTableModel$3.class:na]
	at org.apache.tapestry5.internal.services.PageRenderQueueImpl$Bridge.renderMarkup(PageRenderQueueImpl.java:62) ~[tapestry-core-5.3.7.jar:na]
	at org.got5.tapestry5.jquery.internal.DefaultDataTableModel$3.renderMarkup(DefaultDataTableModel.java:453) ~[DefaultDataTableModel$3.class:na]
	at org.apache.tapestry5.internal.services.PageRenderQueueImpl$Bridge.renderMarkup(PageRenderQueueImpl.java:62) ~[tapestry-core-5.3.7.jar:na]
	at org.got5.tapestry5.jquery.internal.DefaultDataTableModel$3.renderMarkup(DefaultDataTableModel.java:453) ~[DefaultDataTableModel$3.class:na]
	at org.apache.tapestry5.internal.services.PageRenderQueueImpl$Bridge.renderMarkup(PageRenderQueueImpl.java:62) ~[tapestry-core-5.3.7.jar:na]
	at org.got5.tapestry5.jquery.internal.DefaultDataTableModel$3.renderMarkup(DefaultDataTableModel.java:453) ~[DefaultDataTableModel$3.class:na]
	at org.apache.tapestry5.internal.services.PageRenderQueueImpl$Bridge.renderMarkup(PageRenderQueueImpl.java:62) ~[tapestry-core-5.3.7.jar:na]
 ...
```

Is there a workaround I can apply in the DefaultDatatableModel class to be able to show this amount of data?
I can't modify the JVM thread stack size (by using -Xss param on the JVM command line) because my application must be able to run on Tomcat 7, WAS and WebLogic... :sweat:

**Comment by got5** [comment]
Could you share an example in order to reproduce your issue?

**Comment by khaliloooo** [comment]
Easy to reproduce, an example wiith a fake source with **10 columns** and **1000 records per page** : 

### JAVA
```java
import java.util.ArrayList;
import java.util.List;

import javax.inject.Inject;

import org.apache.tapestry5.ComponentResources;
import org.apache.tapestry5.annotations.Property;
import org.apache.tapestry5.beaneditor.BeanModel;
import org.apache.tapestry5.json.JSONLiteral;
import org.apache.tapestry5.json.JSONObject;
import org.apache.tapestry5.services.BeanModelSource;

public class DatatableProblem {
	@Property
	private Obj displayedRow;

	@Property
	private Integer rowIndex;

	@Inject
	private BeanModelSource beanModelSource;

	@Inject
	protected ComponentResources resources;

	public List<Obj> getSource() {
		ArrayList<Obj> list = new ArrayList<Obj>();

		for (int i = 0; i < 1000; i++)
			list.add(new Obj("AAA" + i, "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA", "AAA"));

		return list;
	}

	public BeanModel<Obj> getModel() {
		return beanModelSource.createDisplayModel(Obj.class, resources.getMessages());
	}

	public JSONObject getOptions() {
		JSONObject json = new JSONObject();

		json.put("iDisplayLength", 1000);
		json.put("aLengthMenu", new JSONLiteral("1000"));
		json.put("sDom", "<'clear'>R<\"H\"lr>t<\"F\"ip>");

		return json;
	}

	public class Obj {
		public String col1;
		public String col2;
		public String col3;
		public String col4;
		public String col5;
		public String col6;
		public String col7;
		public String col8;
		public String col9;
		public String col10;

		private Obj(String col1, String col2, String col3, String col4, String col5, String col6, String col7, String col8, String col9, String col10) {
			super();
			this.col1 = col1;
			this.col2 = col2;
			this.col3 = col3;
			this.col4 = col4;
			this.col5 = col5;
			this.col6 = col6;
			this.col7 = col7;
			this.col8 = col8;
			this.col9 = col9;
			this.col10 = col10;
		}
	}
}
```

### TML
```xml
<?xml version="1.0" encoding="UTF-8"?>
<html xmlns:t="http://tapestry.apache.org/schema/tapestry_5_3.xsd" xmlns:p="tapestry:parameter">
	<body>
		<t:jquery.datatable t:id="datatable"
			t:mode="true" t:source="source" t:model="model"
			t:row="displayedRow" t:options="options"
			t:rowIndex="rowIndex" />
	</body>
</html>
```

**Comment by adaptivui** [comment]
Hello,

I was able to reproduce the issue in a jetty container.
AFAIK, there is no easy way to handle programmatically such amount of data for the datatable with the ajax mode (t:mode=true). 
But if you can't use "-Xss" parameter , why don't you paginate your list ? 
Another option would be to use the "normal" mode (t:mode=false)

**Comment by Tokinoki** [comment]
Hello,


I was able to alleviate the problem by modifying the  getResponse method in DefaultDatatableModel.java

```java
		for (int index = startIndex; index <= endIndex; index++) {
			// JSONArray cell = new JSONArray();
			JSONObject cell = new JSONObject();

			rows.put(cell);

			Object obj = source.getRowValue(index);

			List<String> names = model.getPropertyNames();
			int rowIndex = index % rowsPerPage;
			int columnIndex = 0;
			for (String name : names) {
				Block override = overrides.getOverrideBlock(name + "Cell");

				/**
				 * Is the property overridden as a block
				 */
				if (override != null) {
					/**
					 * Render the block from server-side !
					 */
					addPartialMarkupRendererFilter(override, source.getRowType(), obj, name, rowIndex, columnIndex, index);
				} else {

					PropertyConduit conduit = model.get(name).getConduit();

					Object val = (conduit.get(obj) != null) ? conduit.get(obj) : "";

					if (val instanceof String && "".equals(val)) {
						rows.getJSONObject(rowIndex).put(name, val);

					} else if (!String.class.equals(model.get(name).getClass()) && !Number.class.isAssignableFrom(model.get(name).getClass())) {
						Translator<Object> translator = translatorSource.findByType(model.get(name).getPropertyType());
						if (translator != null) {
							val = translator.toClient(val);
						} else {
							val = val.toString();
						}
						
						// Modification HERE !!!
						rows.getJSONObject(rowIndex).put(name, val);
						// /**
						// * Render the value from server-side !
						// */
						// addPartialMarkupRendererFilter(val, source.getRowType(), obj, name, rowIndex, columnIndex, index);
					}

				}
				columnIndex++;
			}

		}
```

**Comment by khaliloooo** [comment]
Unfortunately, this solution solves the problem only if there is not a lot of overrided columns.

**Comment by khaliloooo** [comment]
To @adaptivui : the datatable is paginated but the user can choose 200, 500 or 1000 records per page.
